//
//  PalmOilGlyphs.swift
//  Palm Oil App
//
//  Created by Vladimír Bělohradský on 19/01/16.
//  Copyright (c) 2016 GDGSCL. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class PalmOilGlyphs : NSObject {

    //// Drawing Methods

    public class func drawBarcodeBar(frame frame: CGRect = CGRectMake(11, 7, 172, 71), borderColor: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)) {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX, frame.minY + 30))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 2, frame.minY + 30))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 2, frame.minY))
        bezierPath.addLineToPoint(CGPointMake(frame.minX, frame.minY))
        bezierPath.addLineToPoint(CGPointMake(frame.minX, frame.minY + 30))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 2, frame.minY + 2))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 32, frame.minY + 2))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 32, frame.minY))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 2, frame.minY))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 2, frame.minY + 2))
        bezierPath.closePath()
        borderColor.setFill()
        bezierPath.fill()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(frame.maxX, frame.minY + 30))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.minY + 30))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.minY))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX, frame.minY))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX, frame.minY + 30))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(frame.maxX - 2, frame.minY + 2))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX - 32, frame.minY + 2))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX - 32, frame.minY))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.minY))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.minY + 2))
        bezier2Path.closePath()
        borderColor.setFill()
        bezier2Path.fill()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(frame.maxX, frame.maxY - 30))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.maxY - 30))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.maxY))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX, frame.maxY))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX, frame.maxY - 30))
        bezier3Path.closePath()
        bezier3Path.moveToPoint(CGPointMake(frame.maxX - 2, frame.maxY - 2))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX - 32, frame.maxY - 2))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX - 32, frame.maxY))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.maxY))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.maxY - 2))
        bezier3Path.closePath()
        borderColor.setFill()
        bezier3Path.fill()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(frame.minX, frame.maxY - 30))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX + 2, frame.maxY - 30))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX + 2, frame.maxY))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX, frame.maxY))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX, frame.maxY - 30))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(frame.minX + 2, frame.maxY - 2))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX + 32, frame.maxY - 2))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX + 32, frame.maxY))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX + 2, frame.maxY))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX + 2, frame.maxY - 2))
        bezier4Path.closePath()
        borderColor.setFill()
        bezier4Path.fill()
    }

    public class func drawThumbOK(frame frame: CGRect = CGRectMake(32, 39, 158, 159), thumbColor: UIColor = UIColor(red: 0.652, green: 0.800, blue: 0.320, alpha: 1.000)) {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.84810 * frame.width, frame.minY + 0.49088 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.78752 * frame.width, frame.minY + 0.43331 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.84810 * frame.width, frame.minY + 0.45836 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.82207 * frame.width, frame.minY + 0.43331 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.56965 * frame.width, frame.minY + 0.43331 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.60855 * frame.width, frame.minY + 0.26529 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.58357 * frame.width, frame.minY + 0.40140 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.60855 * frame.width, frame.minY + 0.33443 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.53489 * frame.width, frame.minY + 0.16981 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.60855 * frame.width, frame.minY + 0.18637 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.56850 * frame.width, frame.minY + 0.16981 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.48395 * frame.width, frame.minY + 0.21362 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.51409 * frame.width, frame.minY + 0.16981 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.48395 * frame.width, frame.minY + 0.18541 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.41659 * frame.width, frame.minY + 0.38574 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.48395 * frame.width, frame.minY + 0.22554 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.48206 * frame.width, frame.minY + 0.33148 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.28882 * frame.width, frame.minY + 0.45869 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.34685 * frame.width, frame.minY + 0.44357 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.32704 * frame.width, frame.minY + 0.45869 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.16511 * frame.width, frame.minY + 0.45965 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.24430 * frame.width, frame.minY + 0.45869 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.16511 * frame.width, frame.minY + 0.45965 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.15190 * frame.width, frame.minY + 0.45982 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.15190 * frame.width, frame.minY + 0.76781 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.29769 * frame.width, frame.minY + 0.76781 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.36062 * frame.width, frame.minY + 0.79132 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.30715 * frame.width, frame.minY + 0.76781 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.33558 * frame.width, frame.minY + 0.78031 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.48048 * frame.width, frame.minY + 0.83019 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.40200 * frame.width, frame.minY + 0.80955 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.44892 * frame.width, frame.minY + 0.83019 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.69106 * frame.width, frame.minY + 0.83011 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.75325 * frame.width, frame.minY + 0.77070 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.72536 * frame.width, frame.minY + 0.83011 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.75325 * frame.width, frame.minY + 0.80347 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.74066 * frame.width, frame.minY + 0.73524 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.75325 * frame.width, frame.minY + 0.75737 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.74843 * frame.width, frame.minY + 0.74517 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.78433 * frame.width, frame.minY + 0.67838 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.76577 * frame.width, frame.minY + 0.72813 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.78433 * frame.width, frame.minY + 0.70547 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.77169 * frame.width, frame.minY + 0.64231 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.78433 * frame.width, frame.minY + 0.66477 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.77949 * frame.width, frame.minY + 0.65237 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.81450 * frame.width, frame.minY + 0.58484 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.79642 * frame.width, frame.minY + 0.63450 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.81450 * frame.width, frame.minY + 0.61184 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.80213 * frame.width, frame.minY + 0.54872 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.81450 * frame.width, frame.minY + 0.57128 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.80978 * frame.width, frame.minY + 0.55883 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.84810 * frame.width, frame.minY + 0.49083 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.82847 * frame.width, frame.minY + 0.54222 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.84810 * frame.width, frame.minY + 0.51883 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.84810 * frame.width, frame.minY + 0.49088 * frame.height))
        bezierPath.closePath()
        thumbColor.setFill()
        bezierPath.fill()
    }

    public class func drawThumbKO(frame frame: CGRect = CGRectMake(32, 15, 158, 159), thumbColor: UIColor = UIColor(red: 0.652, green: 0.800, blue: 0.320, alpha: 1.000)) {

        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(frame.minX + 0.15190 * frame.width, frame.minY + 0.50912 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.21248 * frame.width, frame.minY + 0.56669 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.15190 * frame.width, frame.minY + 0.54164 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.17793 * frame.width, frame.minY + 0.56669 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.43035 * frame.width, frame.minY + 0.56669 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.39145 * frame.width, frame.minY + 0.73471 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.41643 * frame.width, frame.minY + 0.59860 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.39145 * frame.width, frame.minY + 0.66557 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.46511 * frame.width, frame.minY + 0.83019 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.39145 * frame.width, frame.minY + 0.81363 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.43150 * frame.width, frame.minY + 0.83019 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.51605 * frame.width, frame.minY + 0.78638 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.48591 * frame.width, frame.minY + 0.83019 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.51605 * frame.width, frame.minY + 0.81459 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.58341 * frame.width, frame.minY + 0.61426 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.51605 * frame.width, frame.minY + 0.77446 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.51794 * frame.width, frame.minY + 0.66852 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.71118 * frame.width, frame.minY + 0.54131 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.65315 * frame.width, frame.minY + 0.55643 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.67296 * frame.width, frame.minY + 0.54131 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.83489 * frame.width, frame.minY + 0.54035 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.75570 * frame.width, frame.minY + 0.54131 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.83489 * frame.width, frame.minY + 0.54035 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.84810 * frame.width, frame.minY + 0.54018 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.84810 * frame.width, frame.minY + 0.23219 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.70231 * frame.width, frame.minY + 0.23219 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.63938 * frame.width, frame.minY + 0.20868 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.69285 * frame.width, frame.minY + 0.23219 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.66442 * frame.width, frame.minY + 0.21969 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.51952 * frame.width, frame.minY + 0.16981 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.59800 * frame.width, frame.minY + 0.19045 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.55108 * frame.width, frame.minY + 0.16981 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.30894 * frame.width, frame.minY + 0.16989 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.24675 * frame.width, frame.minY + 0.22930 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.27464 * frame.width, frame.minY + 0.16989 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.24675 * frame.width, frame.minY + 0.19653 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.25934 * frame.width, frame.minY + 0.26476 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.24675 * frame.width, frame.minY + 0.24263 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.25157 * frame.width, frame.minY + 0.25483 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.21567 * frame.width, frame.minY + 0.32162 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.23423 * frame.width, frame.minY + 0.27187 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.21567 * frame.width, frame.minY + 0.29453 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.22831 * frame.width, frame.minY + 0.35769 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.21567 * frame.width, frame.minY + 0.33523 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.22051 * frame.width, frame.minY + 0.34763 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.18550 * frame.width, frame.minY + 0.41516 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.20358 * frame.width, frame.minY + 0.36550 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.18550 * frame.width, frame.minY + 0.38816 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.19787 * frame.width, frame.minY + 0.45128 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.18550 * frame.width, frame.minY + 0.42872 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.19022 * frame.width, frame.minY + 0.44117 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.15190 * frame.width, frame.minY + 0.50917 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.17153 * frame.width, frame.minY + 0.45778 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.15190 * frame.width, frame.minY + 0.48117 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.15190 * frame.width, frame.minY + 0.50912 * frame.height))
        bezier2Path.closePath()
        thumbColor.setFill()
        bezier2Path.fill()
    }

    public class func drawUnknown(frame frame: CGRect = CGRectMake(22, 20, 158, 159), thumbColor: UIColor = UIColor(red: 0.652, green: 0.800, blue: 0.320, alpha: 1.000)) {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 79.5, frame.minY + 36))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 36, frame.minY + 79.5), controlPoint1: CGPointMake(frame.minX + 55.48, frame.minY + 36), controlPoint2: CGPointMake(frame.minX + 36, frame.minY + 55.48))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 79.5, frame.minY + 123), controlPoint1: CGPointMake(frame.minX + 36, frame.minY + 103.52), controlPoint2: CGPointMake(frame.minX + 55.48, frame.minY + 123))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 123, frame.minY + 79.5), controlPoint1: CGPointMake(frame.minX + 103.52, frame.minY + 123), controlPoint2: CGPointMake(frame.minX + 123, frame.minY + 103.52))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 79.5, frame.minY + 36), controlPoint1: CGPointMake(frame.minX + 123, frame.minY + 55.48), controlPoint2: CGPointMake(frame.minX + 103.52, frame.minY + 36))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 79.5, frame.minY + 102.12))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 76.02, frame.minY + 98.64), controlPoint1: CGPointMake(frame.minX + 77.58, frame.minY + 102.12), controlPoint2: CGPointMake(frame.minX + 76.02, frame.minY + 100.56))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 79.5, frame.minY + 95.16), controlPoint1: CGPointMake(frame.minX + 76.02, frame.minY + 96.72), controlPoint2: CGPointMake(frame.minX + 77.58, frame.minY + 95.16))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 82.98, frame.minY + 98.64), controlPoint1: CGPointMake(frame.minX + 81.42, frame.minY + 95.16), controlPoint2: CGPointMake(frame.minX + 82.98, frame.minY + 96.72))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 79.5, frame.minY + 102.12), controlPoint1: CGPointMake(frame.minX + 82.98, frame.minY + 100.56), controlPoint2: CGPointMake(frame.minX + 81.42, frame.minY + 102.12))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 86.42, frame.minY + 78.32))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 81.65, frame.minY + 88.2), controlPoint1: CGPointMake(frame.minX + 81.76, frame.minY + 82.97), controlPoint2: CGPointMake(frame.minX + 81.88, frame.minY + 82.86))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 77.76, frame.minY + 88.2))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 83.92, frame.minY + 76), controlPoint1: CGPointMake(frame.minX + 77.99, frame.minY + 82.31), controlPoint2: CGPointMake(frame.minX + 79.29, frame.minY + 80.3))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 87.88, frame.minY + 68.14), controlPoint1: CGPointMake(frame.minX + 86.17, frame.minY + 73.87), controlPoint2: CGPointMake(frame.minX + 87.88, frame.minY + 71.31))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 79.17, frame.minY + 59.92), controlPoint1: CGPointMake(frame.minX + 87.88, frame.minY + 63.27), controlPoint2: CGPointMake(frame.minX + 83.92, frame.minY + 59.92))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 69.36, frame.minY + 70.8), controlPoint1: CGPointMake(frame.minX + 72.53, frame.minY + 59.92), controlPoint2: CGPointMake(frame.minX + 69.24, frame.minY + 64.52))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 65.52, frame.minY + 70.8))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 79.35, frame.minY + 56.69), controlPoint1: CGPointMake(frame.minX + 65.59, frame.minY + 62.15), controlPoint2: CGPointMake(frame.minX + 70.52, frame.minY + 56.69))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 91.71, frame.minY + 67.96), controlPoint1: CGPointMake(frame.minX + 86.11, frame.minY + 56.69), controlPoint2: CGPointMake(frame.minX + 91.71, frame.minY + 60.9))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 86.41, frame.minY + 78.32), controlPoint1: CGPointMake(frame.minX + 91.71, frame.minY + 72.47), controlPoint2: CGPointMake(frame.minX + 89.52, frame.minY + 75.39))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 86.42, frame.minY + 78.32))
        bezierPath.closePath()
        thumbColor.setFill()
        bezierPath.fill()
    }

    public class func drawButtonFlash(frame frame: CGRect = CGRectMake(53, 39, 60, 60), buttonColor: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)) {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.66987 * frame.width, frame.minY + 0.48102 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.55253 * frame.width, frame.minY + 0.48102 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.58102 * frame.width, frame.minY + 0.25000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.35000 * frame.width, frame.minY + 0.55210 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.46733 * frame.width, frame.minY + 0.55210 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.43885 * frame.width, frame.minY + 0.78312 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.66987 * frame.width, frame.minY + 0.48102 * frame.height))
        bezierPath.closePath()
        buttonColor.setFill()
        bezierPath.fill()
    }

    public class func drawButtonHistory(frame frame: CGRect = CGRectMake(19, 22, 60, 60), buttonColor: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Page-1
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, frame.minX + 0.49559 * frame.width, frame.minY + 0.50833 * frame.height)



        //// icon-history
        CGContextSaveGState(context)
        CGContextSetAlpha(context, 0.9)
        CGContextBeginTransparencyLayer(context, nil)


        //// Shape-Copy Drawing
        let shapeCopyPath = UIBezierPath()
        shapeCopyPath.moveToPoint(CGPointMake(0.84, -15.5))
        shapeCopyPath.addCurveToPoint(CGPointMake(-12.89, -7.67), controlPoint1: CGPointMake(-5.02, -15.5), controlPoint2: CGPointMake(-10.21, -12.4))
        shapeCopyPath.addLineToPoint(CGPointMake(-16.74, -11.42))
        shapeCopyPath.addLineToPoint(CGPointMake(-16.74, -0.82))
        shapeCopyPath.addLineToPoint(CGPointMake(-5.86, -0.82))
        shapeCopyPath.addLineToPoint(CGPointMake(-10.54, -5.38))
        shapeCopyPath.addCurveToPoint(CGPointMake(0.84, -12.24), controlPoint1: CGPointMake(-8.37, -9.46), controlPoint2: CGPointMake(-4.18, -12.24))
        shapeCopyPath.addCurveToPoint(CGPointMake(13.39, 0), controlPoint1: CGPointMake(7.7, -12.24), controlPoint2: CGPointMake(13.39, -6.69))
        shapeCopyPath.addCurveToPoint(CGPointMake(0.84, 12.24), controlPoint1: CGPointMake(13.39, 6.69), controlPoint2: CGPointMake(7.7, 12.24))
        shapeCopyPath.addCurveToPoint(CGPointMake(-11.05, 4.08), controlPoint1: CGPointMake(-4.69, 12.24), controlPoint2: CGPointMake(-9.2, 8.81))
        shapeCopyPath.addLineToPoint(CGPointMake(-14.56, 4.08))
        shapeCopyPath.addCurveToPoint(CGPointMake(0.84, 15.5), controlPoint1: CGPointMake(-12.72, 10.61), controlPoint2: CGPointMake(-6.53, 15.5))
        shapeCopyPath.addCurveToPoint(CGPointMake(16.74, 0), controlPoint1: CGPointMake(9.71, 15.5), controlPoint2: CGPointMake(16.74, 8.48))
        shapeCopyPath.addCurveToPoint(CGPointMake(0.84, -15.5), controlPoint1: CGPointMake(16.74, -8.48), controlPoint2: CGPointMake(9.54, -15.5))
        shapeCopyPath.addLineToPoint(CGPointMake(0.84, -15.5))
        shapeCopyPath.closePath()
        shapeCopyPath.moveToPoint(CGPointMake(-1.67, -7.34))
        shapeCopyPath.addLineToPoint(CGPointMake(-1.67, 0.98))
        shapeCopyPath.addLineToPoint(CGPointMake(6.19, 5.55))
        shapeCopyPath.addLineToPoint(CGPointMake(7.53, 3.43))
        shapeCopyPath.addLineToPoint(CGPointMake(0.84, -0.49))
        shapeCopyPath.addLineToPoint(CGPointMake(0.84, -7.34))
        shapeCopyPath.addLineToPoint(CGPointMake(-1.67, -7.34))
        shapeCopyPath.addLineToPoint(CGPointMake(-1.67, -7.34))
        shapeCopyPath.closePath()
        shapeCopyPath.miterLimit = 4;

        shapeCopyPath.usesEvenOddFillRule = true;

        buttonColor.setFill()
        shapeCopyPath.fill()


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)



        CGContextRestoreGState(context)
    }

    public class func drawButtonInfo(frame frame: CGRect = CGRectMake(44, 46, 60, 60), buttonColor: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Page-1
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, frame.minX + 0.50449 * frame.width, frame.minY + 0.50000 * frame.height)



        //// icon-info
        //// Shape-Copy-2 Drawing
        let shapeCopy2Path = UIBezierPath()
        shapeCopy2Path.moveToPoint(CGPointMake(3.32, -15))
        shapeCopy2Path.addCurveToPoint(CGPointMake(6.05, -12.06), controlPoint1: CGPointMake(5.14, -15), controlPoint2: CGPointMake(6.05, -13.63))
        shapeCopy2Path.addCurveToPoint(CGPointMake(2.4, -8.3), controlPoint1: CGPointMake(6.05, -10.11), controlPoint2: CGPointMake(4.47, -8.3))
        shapeCopy2Path.addCurveToPoint(CGPointMake(-0.29, -11.28), controlPoint1: CGPointMake(0.67, -8.3), controlPoint2: CGPointMake(-0.34, -9.42))
        shapeCopy2Path.addCurveToPoint(CGPointMake(3.32, -15), controlPoint1: CGPointMake(-0.29, -12.85), controlPoint2: CGPointMake(0.91, -15))
        shapeCopy2Path.addLineToPoint(CGPointMake(3.32, -15))
        shapeCopy2Path.closePath()
        shapeCopy2Path.moveToPoint(CGPointMake(-2.31, 15))
        shapeCopy2Path.addCurveToPoint(CGPointMake(-3.79, 9.72), controlPoint1: CGPointMake(-3.75, 15), controlPoint2: CGPointMake(-4.8, 14.02))
        shapeCopy2Path.addLineToPoint(CGPointMake(-2.14, 2.08))
        shapeCopy2Path.addCurveToPoint(CGPointMake(-2.14, 0.37), controlPoint1: CGPointMake(-1.85, 0.86), controlPoint2: CGPointMake(-1.8, 0.37))
        shapeCopy2Path.addCurveToPoint(CGPointMake(-5.55, 2.04), controlPoint1: CGPointMake(-2.57, 0.37), controlPoint2: CGPointMake(-4.44, 1.21))
        shapeCopy2Path.addLineToPoint(CGPointMake(-6.27, 0.72))
        shapeCopy2Path.addCurveToPoint(CGPointMake(3, -4.48), controlPoint1: CGPointMake(-2.76, -2.56), controlPoint2: CGPointMake(1.27, -4.48))
        shapeCopy2Path.addCurveToPoint(CGPointMake(3.96, 0.37), controlPoint1: CGPointMake(4.44, -4.48), controlPoint2: CGPointMake(4.68, -2.57))
        shapeCopy2Path.addLineToPoint(CGPointMake(2.07, 8.39))
        shapeCopy2Path.addCurveToPoint(CGPointMake(2.21, 10.3), controlPoint1: CGPointMake(1.73, 9.81), controlPoint2: CGPointMake(1.87, 10.3))
        shapeCopy2Path.addCurveToPoint(CGPointMake(5.45, 8.49), controlPoint1: CGPointMake(2.64, 10.3), controlPoint2: CGPointMake(4.06, 9.71))
        shapeCopy2Path.addLineToPoint(CGPointMake(6.27, 9.71))
        shapeCopy2Path.addCurveToPoint(CGPointMake(-2.31, 15), controlPoint1: CGPointMake(2.86, 13.53), controlPoint2: CGPointMake(-0.86, 15))
        shapeCopy2Path.addLineToPoint(CGPointMake(-2.31, 15))
        shapeCopy2Path.closePath()
        shapeCopy2Path.miterLimit = 4;

        shapeCopy2Path.usesEvenOddFillRule = true;

        buttonColor.setFill()
        shapeCopy2Path.fill()





        CGContextRestoreGState(context)
    }

    public class func drawPalmOilLogo(frame frame: CGRect = CGRectMake(0, 503, 208, 308), borderColor: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)) {


        //// Subframes
        let layer_1: CGRect = CGRectMake(frame.minX + floor(frame.width * 0.05134 - 0.18) + 0.68, frame.minY + 25.36, floor(frame.width * 0.93575 - 0.14) - floor(frame.width * 0.05134 - 0.18) - 0.04, frame.height - 44.96)


        //// Layer_1
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(layer_1.minX + 0.30319 * layer_1.width, layer_1.minY + 0.00000 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.44803 * layer_1.width, layer_1.minY + 0.01759 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.35237 * layer_1.width, layer_1.minY + 0.00100 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.40180 * layer_1.width, layer_1.minY + 0.00665 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.21702 * layer_1.width, layer_1.minY + 0.08841 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.34207 * layer_1.width, layer_1.minY + 0.01759 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.21702 * layer_1.width, layer_1.minY + 0.08841 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.57895 * layer_1.width, layer_1.minY + 0.14631 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.52618 * layer_1.width, layer_1.minY + 0.04977 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.57895 * layer_1.width, layer_1.minY + 0.14631 * layer_1.height))
        bezierPath.addLineToPoint(CGPointMake(layer_1.minX + 0.44803 * layer_1.width, layer_1.minY + 0.12701 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.27735 * layer_1.width, layer_1.minY + 0.14617 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.35811 * layer_1.width, layer_1.minY + 0.11403 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.30588 * layer_1.width, layer_1.minY + 0.12428 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.55601 * layer_1.width, layer_1.minY + 0.39848 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.36266 * layer_1.width, layer_1.minY + 0.17289 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.48150 * layer_1.width, layer_1.minY + 0.23860 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.77066 * layer_1.width, layer_1.minY + 0.22062 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.61772 * layer_1.width, layer_1.minY + 0.28845 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.70591 * layer_1.width, layer_1.minY + 0.24093 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.62960 * layer_1.width, layer_1.minY + 0.20477 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.74704 * layer_1.width, layer_1.minY + 0.20248 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.70392 * layer_1.width, layer_1.minY + 0.19405 * layer_1.height))
        bezierPath.addLineToPoint(CGPointMake(layer_1.minX + 0.52135 * layer_1.width, layer_1.minY + 0.22074 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.82055 * layer_1.width, layer_1.minY + 0.17285 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.52135 * layer_1.width, layer_1.minY + 0.22074 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.56496 * layer_1.width, layer_1.minY + 0.14092 * layer_1.height))
        bezierPath.addLineToPoint(CGPointMake(layer_1.minX + 0.91403 * layer_1.width, layer_1.minY + 0.20477 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.91404 * layer_1.width, layer_1.minY + 0.39632 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.91403 * layer_1.width, layer_1.minY + 0.20477 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 1.10746 * layer_1.width, layer_1.minY + 0.34305 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.85920 * layer_1.width, layer_1.minY + 0.25265 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.91404 * layer_1.width, layer_1.minY + 0.39632 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.95592 * layer_1.width, layer_1.minY + 0.28260 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.74914 * layer_1.width, layer_1.minY + 0.39632 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.85927 * layer_1.width, layer_1.minY + 0.29868 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.84665 * layer_1.width, layer_1.minY + 0.39441 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.74914 * layer_1.width, layer_1.minY + 0.39632 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.74913 * layer_1.width, layer_1.minY + 0.39632 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.74914 * layer_1.width, layer_1.minY + 0.39632 * layer_1.height))
        bezierPath.addLineToPoint(CGPointMake(layer_1.minX + 0.74914 * layer_1.width, layer_1.minY + 0.39632 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.78783 * layer_1.width, layer_1.minY + 0.24075 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.77872 * layer_1.width, layer_1.minY + 0.35170 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.80919 * layer_1.width, layer_1.minY + 0.28817 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.62882 * layer_1.width, layer_1.minY + 0.46623 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.67053 * layer_1.width, layer_1.minY + 0.31260 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.63533 * layer_1.width, layer_1.minY + 0.39911 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.60050 * layer_1.width, layer_1.minY + 0.53484 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.62636 * layer_1.width, layer_1.minY + 0.49162 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.61420 * layer_1.width, layer_1.minY + 0.51542 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.80738 * layer_1.width, layer_1.minY + 0.83729 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.67105 * layer_1.width, layer_1.minY + 0.66650 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.80738 * layer_1.width, layer_1.minY + 0.71727 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.54917 * layer_1.width, layer_1.minY + 1.00000 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.80738 * layer_1.width, layer_1.minY + 0.92714 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.68919 * layer_1.width, layer_1.minY + 1.00000 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.29096 * layer_1.width, layer_1.minY + 0.83729 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.40915 * layer_1.width, layer_1.minY + 1.00000 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.29096 * layer_1.width, layer_1.minY + 0.92714 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.48906 * layer_1.width, layer_1.minY + 0.55009 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.29096 * layer_1.width, layer_1.minY + 0.72202 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.41664 * layer_1.width, layer_1.minY + 0.67062 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.45022 * layer_1.width, layer_1.minY + 0.46065 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.47094 * layer_1.width, layer_1.minY + 0.52773 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.45165 * layer_1.width, layer_1.minY + 0.49592 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.25669 * layer_1.width, layer_1.minY + 0.17055 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.44684 * layer_1.width, layer_1.minY + 0.37747 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.53272 * layer_1.width, layer_1.minY + 0.33962 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.26407 * layer_1.width, layer_1.minY + 0.28437 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.23942 * layer_1.width, layer_1.minY + 0.20759 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.24957 * layer_1.width, layer_1.minY + 0.24765 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.30346 * layer_1.width, layer_1.minY + 0.35874 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.27405 * layer_1.width, layer_1.minY + 0.30964 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.28686 * layer_1.width, layer_1.minY + 0.33487 * layer_1.height))
        bezierPath.addLineToPoint(CGPointMake(layer_1.minX + 0.30346 * layer_1.width, layer_1.minY + 0.35874 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.30346 * layer_1.width, layer_1.minY + 0.35874 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.30347 * layer_1.width, layer_1.minY + 0.35875 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.30347 * layer_1.width, layer_1.minY + 0.35875 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.17036 * layer_1.width, layer_1.minY + 0.18494 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.18677 * layer_1.width, layer_1.minY + 0.35667 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.16905 * layer_1.width, layer_1.minY + 0.24006 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.10395 * layer_1.width, layer_1.minY + 0.35874 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.05339 * layer_1.width, layer_1.minY + 0.22118 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.10395 * layer_1.width, layer_1.minY + 0.35874 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.10395 * layer_1.width, layer_1.minY + 0.12701 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + -0.12994 * layer_1.width, layer_1.minY + 0.29429 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.10395 * layer_1.width, layer_1.minY + 0.12701 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.18095 * layer_1.width, layer_1.minY + 0.01933 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.10552 * layer_1.width, layer_1.minY + 0.08632 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.12487 * layer_1.width, layer_1.minY + 0.04288 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.30319 * layer_1.width, layer_1.minY + 0.00000 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.21738 * layer_1.width, layer_1.minY + 0.00402 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.26052 * layer_1.width, layer_1.minY + 0.00028 * layer_1.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(layer_1.minX + 0.50298 * layer_1.width, layer_1.minY + 0.65886 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.49338 * layer_1.width, layer_1.minY + 0.66250 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.49886 * layer_1.width, layer_1.minY + 0.65915 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.49574 * layer_1.width, layer_1.minY + 0.66037 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.45665 * layer_1.width, layer_1.minY + 0.69635 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.48298 * layer_1.width, layer_1.minY + 0.67354 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.47019 * layer_1.width, layer_1.minY + 0.68463 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.36438 * layer_1.width, layer_1.minY + 0.84123 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.41340 * layer_1.width, layer_1.minY + 0.73380 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.36438 * layer_1.width, layer_1.minY + 0.77625 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.41770 * layer_1.width, layer_1.minY + 0.87556 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.36438 * layer_1.width, layer_1.minY + 0.86016 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.38830 * layer_1.width, layer_1.minY + 0.87556 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.47104 * layer_1.width, layer_1.minY + 0.83520 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.44349 * layer_1.width, layer_1.minY + 0.87556 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.47104 * layer_1.width, layer_1.minY + 0.86497 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.51052 * layer_1.width, layer_1.minY + 0.69072 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.47104 * layer_1.width, layer_1.minY + 0.78019 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.49201 * layer_1.width, layer_1.minY + 0.73266 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.51921 * layer_1.width, layer_1.minY + 0.67078 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.51354 * layer_1.width, layer_1.minY + 0.68387 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.51647 * layer_1.width, layer_1.minY + 0.67723 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.51673 * layer_1.width, layer_1.minY + 0.66267 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.52039 * layer_1.width, layer_1.minY + 0.66801 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.51948 * layer_1.width, layer_1.minY + 0.66505 * layer_1.height))
        bezierPath.addCurveToPoint(CGPointMake(layer_1.minX + 0.50298 * layer_1.width, layer_1.minY + 0.65886 * layer_1.height), controlPoint1: CGPointMake(layer_1.minX + 0.51241 * layer_1.width, layer_1.minY + 0.65932 * layer_1.height), controlPoint2: CGPointMake(layer_1.minX + 0.50940 * layer_1.width, layer_1.minY + 0.65915 * layer_1.height))
        bezierPath.closePath()
        bezierPath.miterLimit = 4;

        borderColor.setFill()
        bezierPath.fill()
    }

    public class func drawShadow(frame frame: CGRect = CGRectMake(0, 69, 240, 25)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Gradient Declarations
        let gradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [UIColor.clearColor().CGColor, UIColor.clearColor().blendedColorWithFraction(0.5, ofColor: UIColor.blackColor()).CGColor, UIColor.blackColor().CGColor], [0, 0.46, 0.68])!

        //// Oval Drawing
        let ovalRect = CGRectMake(frame.minX, frame.minY, frame.width, frame.height + 25)
        let ovalPath = UIBezierPath(ovalInRect: ovalRect)
        CGContextSaveGState(context)
        ovalPath.addClip()
        CGContextDrawLinearGradient(context, gradient,
            CGPointMake(ovalRect.midX, ovalRect.minY),
            CGPointMake(ovalRect.midX, ovalRect.maxY),
            CGGradientDrawingOptions())
        CGContextRestoreGState(context)
    }

}



extension UIColor {
    func blendedColorWithFraction(fraction: CGFloat, ofColor color: UIColor) -> UIColor {
        var r1: CGFloat = 1.0, g1: CGFloat = 1.0, b1: CGFloat = 1.0, a1: CGFloat = 1.0
        var r2: CGFloat = 1.0, g2: CGFloat = 1.0, b2: CGFloat = 1.0, a2: CGFloat = 1.0

        self.getRed(&r1, green: &g1, blue: &b1, alpha: &a1)
        color.getRed(&r2, green: &g2, blue: &b2, alpha: &a2)

        return UIColor(red: r1 * (1 - fraction) + r2 * fraction,
            green: g1 * (1 - fraction) + g2 * fraction,
            blue: b1 * (1 - fraction) + b2 * fraction,
            alpha: a1 * (1 - fraction) + a2 * fraction);
    }
}
