//
//  PalmOilGlyphs.swift
//  Palm Oil App
//
//  Created by Vladimír Bělohradský on 12/04/15.
//  Copyright (c) 2015 GDGSCL. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class PalmOilGlyphs : NSObject {

    //// Drawing Methods

    public class func drawBarcodeBar(#frame: CGRect, borderColor: UIColor) {

        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX, frame.minY + 30))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 2, frame.minY + 30))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 2, frame.minY))
        bezierPath.addLineToPoint(CGPointMake(frame.minX, frame.minY))
        bezierPath.addLineToPoint(CGPointMake(frame.minX, frame.minY + 30))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 2, frame.minY + 2))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 32, frame.minY + 2))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 32, frame.minY))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 2, frame.minY))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 2, frame.minY + 2))
        bezierPath.closePath()
        borderColor.setFill()
        bezierPath.fill()


        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(frame.maxX, frame.minY + 30))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.minY + 30))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.minY))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX, frame.minY))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX, frame.minY + 30))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(frame.maxX - 2, frame.minY + 2))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX - 32, frame.minY + 2))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX - 32, frame.minY))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.minY))
        bezier2Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.minY + 2))
        bezier2Path.closePath()
        borderColor.setFill()
        bezier2Path.fill()


        //// Bezier 3 Drawing
        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(frame.maxX, frame.maxY - 30))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.maxY - 30))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.maxY))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX, frame.maxY))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX, frame.maxY - 30))
        bezier3Path.closePath()
        bezier3Path.moveToPoint(CGPointMake(frame.maxX - 2, frame.maxY - 2))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX - 32, frame.maxY - 2))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX - 32, frame.maxY))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.maxY))
        bezier3Path.addLineToPoint(CGPointMake(frame.maxX - 2, frame.maxY - 2))
        bezier3Path.closePath()
        borderColor.setFill()
        bezier3Path.fill()


        //// Bezier 4 Drawing
        var bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(frame.minX, frame.maxY - 30))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX + 2, frame.maxY - 30))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX + 2, frame.maxY))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX, frame.maxY))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX, frame.maxY - 30))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(frame.minX + 2, frame.maxY - 2))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX + 32, frame.maxY - 2))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX + 32, frame.maxY))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX + 2, frame.maxY))
        bezier4Path.addLineToPoint(CGPointMake(frame.minX + 2, frame.maxY - 2))
        bezier4Path.closePath()
        borderColor.setFill()
        bezier4Path.fill()
    }

    public class func drawThumbOK(#frame: CGRect, thumbColor: UIColor) {


        //// Subframes
        let page1: CGRect = CGRectMake(frame.minX + 17.14, frame.minY + 17.26, frame.width - 30.37, frame.height - 39.74)


        //// Page-1
        //// icon-thumb
        //// thumbsup
        //// Shape-Copy-3 Drawing
        var shapeCopy3Path = UIBezierPath()
        shapeCopy3Path.moveToPoint(CGPointMake(page1.minX + 0.09598 * page1.width, page1.minY + 0.42902 * page1.height))
        shapeCopy3Path.addLineToPoint(CGPointMake(page1.minX + 0.05062 * page1.width, page1.minY + 0.42902 * page1.height))
        shapeCopy3Path.addCurveToPoint(CGPointMake(page1.minX + 0.00000 * page1.width, page1.minY + 0.48292 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.02268 * page1.width, page1.minY + 0.42902 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.00000 * page1.width, page1.minY + 0.45316 * page1.height))
        shapeCopy3Path.addLineToPoint(CGPointMake(page1.minX + 0.00000 * page1.width, page1.minY + 0.94535 * page1.height))
        shapeCopy3Path.addCurveToPoint(CGPointMake(page1.minX + 0.05062 * page1.width, page1.minY + 0.99925 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.00000 * page1.width, page1.minY + 0.97510 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.02268 * page1.width, page1.minY + 0.99925 * page1.height))
        shapeCopy3Path.addLineToPoint(CGPointMake(page1.minX + 0.09588 * page1.width, page1.minY + 0.99925 * page1.height))
        shapeCopy3Path.addCurveToPoint(CGPointMake(page1.minX + 0.14650 * page1.width, page1.minY + 0.94535 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.12382 * page1.width, page1.minY + 0.99925 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.14650 * page1.width, page1.minY + 0.97510 * page1.height))
        shapeCopy3Path.addLineToPoint(CGPointMake(page1.minX + 0.14650 * page1.width, page1.minY + 0.48292 * page1.height))
        shapeCopy3Path.addCurveToPoint(CGPointMake(page1.minX + 0.09598 * page1.width, page1.minY + 0.42902 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.14660 * page1.width, page1.minY + 0.45316 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.12392 * page1.width, page1.minY + 0.42902 * page1.height))
        shapeCopy3Path.addLineToPoint(CGPointMake(page1.minX + 0.09598 * page1.width, page1.minY + 0.42902 * page1.height))
        shapeCopy3Path.closePath()
        shapeCopy3Path.miterLimit = 4;

        shapeCopy3Path.usesEvenOddFillRule = true;

        thumbColor.setFill()
        shapeCopy3Path.fill()


        //// Shape-Copy-4 Drawing
        var shapeCopy4Path = UIBezierPath()
        shapeCopy4Path.moveToPoint(CGPointMake(page1.minX + 0.94938 * page1.width, page1.minY + 0.35281 * page1.height))
        shapeCopy4Path.addLineToPoint(CGPointMake(page1.minX + 0.58967 * page1.width, page1.minY + 0.35238 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.61427 * page1.width, page1.minY + 0.21893 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.58967 * page1.width, page1.minY + 0.35238 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.61052 * page1.width, page1.minY + 0.26151 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.61113 * page1.width, page1.minY + 0.13215 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.61680 * page1.width, page1.minY + 0.18982 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.61741 * page1.width, page1.minY + 0.16083 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.57478 * page1.width, page1.minY + 0.02867 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.60181 * page1.width, page1.minY + 0.08904 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.59139 * page1.width, page1.minY + 0.06209 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.52993 * page1.width, page1.minY + 0.00000 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.56587 * page1.width, page1.minY + 0.01099 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.54866 * page1.width, page1.minY + 0.00000 * page1.height))
        shapeCopy4Path.addLineToPoint(CGPointMake(page1.minX + 0.46028 * page1.width, page1.minY + 0.00000 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.40966 * page1.width, page1.minY + 0.05411 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.43223 * page1.width, page1.minY + 0.00000 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.40955 * page1.width, page1.minY + 0.02425 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.40885 * page1.width, page1.minY + 0.17290 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.40986 * page1.width, page1.minY + 0.10402 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.40986 * page1.width, page1.minY + 0.17064 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.31408 * page1.width, page1.minY + 0.34893 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.38151 * page1.width, page1.minY + 0.23413 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.34982 * page1.width, page1.minY + 0.29288 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.26083 * page1.width, page1.minY + 0.42223 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.29778 * page1.width, page1.minY + 0.37458 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.28067 * page1.width, page1.minY + 0.39948 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.24736 * page1.width, page1.minY + 0.45877 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.25212 * page1.width, page1.minY + 0.43214 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.24736 * page1.width, page1.minY + 0.44530 * page1.height))
        shapeCopy4Path.addLineToPoint(CGPointMake(page1.minX + 0.24736 * page1.width, page1.minY + 0.93004 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.26154 * page1.width, page1.minY + 0.96745 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.24736 * page1.width, page1.minY + 0.94395 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.25243 * page1.width, page1.minY + 0.95742 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.33929 * page1.width, page1.minY + 1.00000 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.27510 * page1.width, page1.minY + 0.98232 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.29940 * page1.width, page1.minY + 1.00000 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.81402 * page1.width, page1.minY + 0.99935 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.46514 * page1.width, page1.minY + 0.99946 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.66904 * page1.width, page1.minY + 0.99828 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.85806 * page1.width, page1.minY + 0.97262 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.83214 * page1.width, page1.minY + 0.99946 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.84895 * page1.width, page1.minY + 0.98933 * page1.height))
        shapeCopy4Path.addLineToPoint(CGPointMake(page1.minX + 0.98593 * page1.width, page1.minY + 0.73957 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.99929 * page1.width, page1.minY + 0.68643 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.99464 * page1.width, page1.minY + 0.72340 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.99919 * page1.width, page1.minY + 0.70508 * page1.height))
        shapeCopy4Path.addLineToPoint(CGPointMake(page1.minX + 1.00000 * page1.width, page1.minY + 0.40692 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.94938 * page1.width, page1.minY + 0.35281 * page1.height), controlPoint1: CGPointMake(page1.minX + 1.00000 * page1.width, page1.minY + 0.37706 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.97732 * page1.width, page1.minY + 0.35292 * page1.height))
        shapeCopy4Path.addLineToPoint(CGPointMake(page1.minX + 0.94938 * page1.width, page1.minY + 0.35281 * page1.height))
        shapeCopy4Path.closePath()
        shapeCopy4Path.miterLimit = 4;

        shapeCopy4Path.usesEvenOddFillRule = true;

        thumbColor.setFill()
        shapeCopy4Path.fill()
    }

    public class func drawThumbKO(#frame: CGRect, thumbColor: UIColor) {


        //// Subframes
        let page1: CGRect = CGRectMake(frame.minX + 17.24, frame.minY + 17.48, frame.width - 30.37, frame.height - 39.74)


        //// Page-1
        //// icon-thumb
        //// thumbsup
        //// Shape-Copy-3 Drawing
        var shapeCopy3Path = UIBezierPath()
        shapeCopy3Path.moveToPoint(CGPointMake(page1.minX + 0.90402 * page1.width, page1.minY + 0.57098 * page1.height))
        shapeCopy3Path.addLineToPoint(CGPointMake(page1.minX + 0.94938 * page1.width, page1.minY + 0.57098 * page1.height))
        shapeCopy3Path.addCurveToPoint(CGPointMake(page1.minX + 1.00000 * page1.width, page1.minY + 0.51708 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.97732 * page1.width, page1.minY + 0.57098 * page1.height), controlPoint2: CGPointMake(page1.minX + 1.00000 * page1.width, page1.minY + 0.54684 * page1.height))
        shapeCopy3Path.addLineToPoint(CGPointMake(page1.minX + 1.00000 * page1.width, page1.minY + 0.05465 * page1.height))
        shapeCopy3Path.addCurveToPoint(CGPointMake(page1.minX + 0.94938 * page1.width, page1.minY + 0.00075 * page1.height), controlPoint1: CGPointMake(page1.minX + 1.00000 * page1.width, page1.minY + 0.02490 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.97732 * page1.width, page1.minY + 0.00075 * page1.height))
        shapeCopy3Path.addLineToPoint(CGPointMake(page1.minX + 0.90412 * page1.width, page1.minY + 0.00075 * page1.height))
        shapeCopy3Path.addCurveToPoint(CGPointMake(page1.minX + 0.85350 * page1.width, page1.minY + 0.05465 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.87618 * page1.width, page1.minY + 0.00075 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.85350 * page1.width, page1.minY + 0.02490 * page1.height))
        shapeCopy3Path.addLineToPoint(CGPointMake(page1.minX + 0.85350 * page1.width, page1.minY + 0.51708 * page1.height))
        shapeCopy3Path.addCurveToPoint(CGPointMake(page1.minX + 0.90402 * page1.width, page1.minY + 0.57098 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.85340 * page1.width, page1.minY + 0.54684 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.87608 * page1.width, page1.minY + 0.57098 * page1.height))
        shapeCopy3Path.addLineToPoint(CGPointMake(page1.minX + 0.90402 * page1.width, page1.minY + 0.57098 * page1.height))
        shapeCopy3Path.closePath()
        shapeCopy3Path.miterLimit = 4;

        shapeCopy3Path.usesEvenOddFillRule = true;

        thumbColor.setFill()
        shapeCopy3Path.fill()


        //// Shape-Copy-4 Drawing
        var shapeCopy4Path = UIBezierPath()
        shapeCopy4Path.moveToPoint(CGPointMake(page1.minX + 0.05062 * page1.width, page1.minY + 0.64719 * page1.height))
        shapeCopy4Path.addLineToPoint(CGPointMake(page1.minX + 0.41033 * page1.width, page1.minY + 0.64762 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.38573 * page1.width, page1.minY + 0.78107 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.41033 * page1.width, page1.minY + 0.64762 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.38948 * page1.width, page1.minY + 0.73849 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.38887 * page1.width, page1.minY + 0.86785 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.38320 * page1.width, page1.minY + 0.81018 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.38259 * page1.width, page1.minY + 0.83917 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.42522 * page1.width, page1.minY + 0.97133 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.39819 * page1.width, page1.minY + 0.91096 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.40861 * page1.width, page1.minY + 0.93791 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.47007 * page1.width, page1.minY + 1.00000 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.43413 * page1.width, page1.minY + 0.98901 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.45134 * page1.width, page1.minY + 1.00000 * page1.height))
        shapeCopy4Path.addLineToPoint(CGPointMake(page1.minX + 0.53972 * page1.width, page1.minY + 1.00000 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.59034 * page1.width, page1.minY + 0.94589 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.56777 * page1.width, page1.minY + 1.00000 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.59045 * page1.width, page1.minY + 0.97575 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.59115 * page1.width, page1.minY + 0.82710 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.59014 * page1.width, page1.minY + 0.89598 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.59014 * page1.width, page1.minY + 0.82936 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.68592 * page1.width, page1.minY + 0.65107 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.61849 * page1.width, page1.minY + 0.76587 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.65018 * page1.width, page1.minY + 0.70712 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.73917 * page1.width, page1.minY + 0.57777 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.70222 * page1.width, page1.minY + 0.62542 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.71933 * page1.width, page1.minY + 0.60052 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.75264 * page1.width, page1.minY + 0.54123 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.74788 * page1.width, page1.minY + 0.56786 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.75264 * page1.width, page1.minY + 0.55470 * page1.height))
        shapeCopy4Path.addLineToPoint(CGPointMake(page1.minX + 0.75264 * page1.width, page1.minY + 0.06996 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.73846 * page1.width, page1.minY + 0.03255 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.75264 * page1.width, page1.minY + 0.05605 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.74757 * page1.width, page1.minY + 0.04258 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.66071 * page1.width, page1.minY + 0.00000 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.72490 * page1.width, page1.minY + 0.01768 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.70060 * page1.width, page1.minY + 0.00000 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.18598 * page1.width, page1.minY + 0.00065 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.53486 * page1.width, page1.minY + 0.00054 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.33096 * page1.width, page1.minY + 0.00172 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.14194 * page1.width, page1.minY + 0.02738 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.16786 * page1.width, page1.minY + 0.00054 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.15105 * page1.width, page1.minY + 0.01067 * page1.height))
        shapeCopy4Path.addLineToPoint(CGPointMake(page1.minX + 0.01407 * page1.width, page1.minY + 0.26043 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.00071 * page1.width, page1.minY + 0.31357 * page1.height), controlPoint1: CGPointMake(page1.minX + 0.00536 * page1.width, page1.minY + 0.27660 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.00081 * page1.width, page1.minY + 0.29492 * page1.height))
        shapeCopy4Path.addLineToPoint(CGPointMake(page1.minX + 0.00000 * page1.width, page1.minY + 0.59308 * page1.height))
        shapeCopy4Path.addCurveToPoint(CGPointMake(page1.minX + 0.05062 * page1.width, page1.minY + 0.64719 * page1.height), controlPoint1: CGPointMake(page1.minX + -0.00000 * page1.width, page1.minY + 0.62294 * page1.height), controlPoint2: CGPointMake(page1.minX + 0.02268 * page1.width, page1.minY + 0.64708 * page1.height))
        shapeCopy4Path.addLineToPoint(CGPointMake(page1.minX + 0.05062 * page1.width, page1.minY + 0.64719 * page1.height))
        shapeCopy4Path.closePath()
        shapeCopy4Path.miterLimit = 4;

        shapeCopy4Path.usesEvenOddFillRule = true;

        thumbColor.setFill()
        shapeCopy4Path.fill()
    }

    public class func drawButtonFlash(#frame: CGRect, buttonColor: UIColor) {


        //// Subframes
        let page1: CGRect = CGRectMake(frame.minX + floor((frame.width - 23.16) * 0.50055 + 0.06) + 0.44, frame.minY + 10, 23.16, frame.height - 21)


        //// Page-1
        //// icon-flash
        //// Shape Drawing
        var shapePath = UIBezierPath()
        shapePath.moveToPoint(CGPointMake(page1.minX + 20.87, page1.minY + 0.00000 * page1.height))
        shapePath.addLineToPoint(CGPointMake(page1.minX, page1.minY + 0.56860 * page1.height))
        shapePath.addLineToPoint(CGPointMake(page1.minX + 7.74, page1.minY + 0.56860 * page1.height))
        shapePath.addLineToPoint(CGPointMake(page1.minX + 1.79, page1.minY + 1.00000 * page1.height))
        shapePath.addLineToPoint(CGPointMake(page1.minX + 23.16, page1.minY + 0.43137 * page1.height))
        shapePath.addLineToPoint(CGPointMake(page1.minX + 15.42, page1.minY + 0.43137 * page1.height))
        shapePath.addLineToPoint(CGPointMake(page1.minX + 20.87, page1.minY + 0.00000 * page1.height))
        shapePath.closePath()
        shapePath.miterLimit = 4;

        shapePath.usesEvenOddFillRule = true;

        buttonColor.setFill()
        shapePath.fill()
    }

    public class func drawButtonHistory(#frame: CGRect, buttonColor: UIColor) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Subframes
        let page1: CGRect = CGRectMake(frame.minX + floor((frame.width - 42.47) * 0.51342 + 0.5), frame.minY + 10, 42.47, frame.height - 21)


        //// Page-1
        //// icon-history
        CGContextSaveGState(context)
        CGContextSetAlpha(context, 0.9)
        CGContextBeginTransparencyLayer(context, nil)


        //// Shape-Copy Drawing
        var shapeCopyPath = UIBezierPath()
        shapeCopyPath.moveToPoint(CGPointMake(page1.minX + 22.3, page1.minY + 0.00000 * page1.height))
        shapeCopyPath.addCurveToPoint(CGPointMake(page1.minX + 4.88, page1.minY + 0.25263 * page1.height), controlPoint1: CGPointMake(page1.minX + 14.86, page1.minY + 0.00000 * page1.height), controlPoint2: CGPointMake(page1.minX + 8.28, page1.minY + 0.10000 * page1.height))
        shapeCopyPath.addLineToPoint(CGPointMake(page1.minX, page1.minY + 0.13158 * page1.height))
        shapeCopyPath.addLineToPoint(CGPointMake(page1.minX, page1.minY + 0.47368 * page1.height))
        shapeCopyPath.addLineToPoint(CGPointMake(page1.minX + 13.8, page1.minY + 0.47368 * page1.height))
        shapeCopyPath.addLineToPoint(CGPointMake(page1.minX + 7.86, page1.minY + 0.32632 * page1.height))
        shapeCopyPath.addCurveToPoint(CGPointMake(page1.minX + 22.3, page1.minY + 0.10526 * page1.height), controlPoint1: CGPointMake(page1.minX + 10.62, page1.minY + 0.19474 * page1.height), controlPoint2: CGPointMake(page1.minX + 15.93, page1.minY + 0.10526 * page1.height))
        shapeCopyPath.addCurveToPoint(CGPointMake(page1.minX + 38.22, page1.minY + 0.50000 * page1.height), controlPoint1: CGPointMake(page1.minX + 31, page1.minY + 0.10526 * page1.height), controlPoint2: CGPointMake(page1.minX + 38.22, page1.minY + 0.28421 * page1.height))
        shapeCopyPath.addCurveToPoint(CGPointMake(page1.minX + 22.3, page1.minY + 0.89474 * page1.height), controlPoint1: CGPointMake(page1.minX + 38.22, page1.minY + 0.71579 * page1.height), controlPoint2: CGPointMake(page1.minX + 31, page1.minY + 0.89474 * page1.height))
        shapeCopyPath.addCurveToPoint(CGPointMake(page1.minX + 7.22, page1.minY + 0.63158 * page1.height), controlPoint1: CGPointMake(page1.minX + 15.29, page1.minY + 0.89474 * page1.height), controlPoint2: CGPointMake(page1.minX + 9.56, page1.minY + 0.78421 * page1.height))
        shapeCopyPath.addLineToPoint(CGPointMake(page1.minX + 2.76, page1.minY + 0.63158 * page1.height))
        shapeCopyPath.addCurveToPoint(CGPointMake(page1.minX + 22.3, page1.minY + 1.00000 * page1.height), controlPoint1: CGPointMake(page1.minX + 5.1, page1.minY + 0.84211 * page1.height), controlPoint2: CGPointMake(page1.minX + 12.95, page1.minY + 1.00000 * page1.height))
        shapeCopyPath.addCurveToPoint(CGPointMake(page1.minX + 42.47, page1.minY + 0.50000 * page1.height), controlPoint1: CGPointMake(page1.minX + 33.55, page1.minY + 1.00000 * page1.height), controlPoint2: CGPointMake(page1.minX + 42.47, page1.minY + 0.77368 * page1.height))
        shapeCopyPath.addCurveToPoint(CGPointMake(page1.minX + 22.3, page1.minY + 0.00000 * page1.height), controlPoint1: CGPointMake(page1.minX + 42.47, page1.minY + 0.22632 * page1.height), controlPoint2: CGPointMake(page1.minX + 33.34, page1.minY + 0.00000 * page1.height))
        shapeCopyPath.addLineToPoint(CGPointMake(page1.minX + 22.3, page1.minY + 0.00000 * page1.height))
        shapeCopyPath.closePath()
        shapeCopyPath.moveToPoint(CGPointMake(page1.minX + 19.11, page1.minY + 0.26316 * page1.height))
        shapeCopyPath.addLineToPoint(CGPointMake(page1.minX + 19.11, page1.minY + 0.53158 * page1.height))
        shapeCopyPath.addLineToPoint(CGPointMake(page1.minX + 29.09, page1.minY + 0.67895 * page1.height))
        shapeCopyPath.addLineToPoint(CGPointMake(page1.minX + 30.79, page1.minY + 0.61053 * page1.height))
        shapeCopyPath.addLineToPoint(CGPointMake(page1.minX + 22.3, page1.minY + 0.48421 * page1.height))
        shapeCopyPath.addLineToPoint(CGPointMake(page1.minX + 22.3, page1.minY + 0.26316 * page1.height))
        shapeCopyPath.addLineToPoint(CGPointMake(page1.minX + 19.11, page1.minY + 0.26316 * page1.height))
        shapeCopyPath.addLineToPoint(CGPointMake(page1.minX + 19.11, page1.minY + 0.26316 * page1.height))
        shapeCopyPath.closePath()
        shapeCopyPath.miterLimit = 4;

        shapeCopyPath.usesEvenOddFillRule = true;

        buttonColor.setFill()
        shapeCopyPath.fill()


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

    public class func drawButtonInfo(#frame: CGRect, buttonColor: UIColor) {


        //// Subframes
        let page1: CGRect = CGRectMake(frame.minX + floor((frame.width - 16.54) * 0.50619 + 0.5), frame.minY + 11, 16.54, frame.height - 22)


        //// Page-1
        //// icon-info
        //// Shape-Copy-2 Drawing
        var shapeCopy2Path = UIBezierPath()
        shapeCopy2Path.moveToPoint(CGPointMake(page1.minX + 12.64, page1.minY + 0.00000 * page1.height))
        shapeCopy2Path.addCurveToPoint(CGPointMake(page1.minX + 16.25, page1.minY + 0.09789 * page1.height), controlPoint1: CGPointMake(page1.minX + 15.05, page1.minY + 0.00000 * page1.height), controlPoint2: CGPointMake(page1.minX + 16.25, page1.minY + 0.04567 * page1.height))
        shapeCopy2Path.addCurveToPoint(CGPointMake(page1.minX + 11.44, page1.minY + 0.22344 * page1.height), controlPoint1: CGPointMake(page1.minX + 16.25, page1.minY + 0.16311 * page1.height), controlPoint2: CGPointMake(page1.minX + 14.16, page1.minY + 0.22344 * page1.height))
        shapeCopy2Path.addCurveToPoint(CGPointMake(page1.minX + 7.89, page1.minY + 0.12397 * page1.height), controlPoint1: CGPointMake(page1.minX + 9.16, page1.minY + 0.22344 * page1.height), controlPoint2: CGPointMake(page1.minX + 7.83, page1.minY + 0.18592 * page1.height))
        shapeCopy2Path.addCurveToPoint(CGPointMake(page1.minX + 12.64, page1.minY + 0.00000 * page1.height), controlPoint1: CGPointMake(page1.minX + 7.89, page1.minY + 0.07176 * page1.height), controlPoint2: CGPointMake(page1.minX + 9.47, page1.minY + 0.00000 * page1.height))
        shapeCopy2Path.addLineToPoint(CGPointMake(page1.minX + 12.64, page1.minY + 0.00000 * page1.height))
        shapeCopy2Path.closePath()
        shapeCopy2Path.moveToPoint(CGPointMake(page1.minX + 5.23, page1.minY + 1.00000 * page1.height))
        shapeCopy2Path.addCurveToPoint(CGPointMake(page1.minX + 3.26, page1.minY + 0.82385 * page1.height), controlPoint1: CGPointMake(page1.minX + 3.33, page1.minY + 1.00000 * page1.height), controlPoint2: CGPointMake(page1.minX + 1.93, page1.minY + 0.96738 * page1.height))
        shapeCopy2Path.addLineToPoint(CGPointMake(page1.minX + 5.45, page1.minY + 0.56928 * page1.height))
        shapeCopy2Path.addCurveToPoint(CGPointMake(page1.minX + 5.45, page1.minY + 0.51221 * page1.height), controlPoint1: CGPointMake(page1.minX + 5.83, page1.minY + 0.52851 * page1.height), controlPoint2: CGPointMake(page1.minX + 5.89, page1.minY + 0.51221 * page1.height))
        shapeCopy2Path.addCurveToPoint(CGPointMake(page1.minX + 0.95, page1.minY + 0.56811 * page1.height), controlPoint1: CGPointMake(page1.minX + 4.88, page1.minY + 0.51221 * page1.height), controlPoint2: CGPointMake(page1.minX + 2.41, page1.minY + 0.54037 * page1.height))
        shapeCopy2Path.addLineToPoint(CGPointMake(page1.minX, page1.minY + 0.52406 * page1.height))
        shapeCopy2Path.addCurveToPoint(CGPointMake(page1.minX + 12.23, page1.minY + 0.35072 * page1.height), controlPoint1: CGPointMake(page1.minX + 4.62, page1.minY + 0.41480 * page1.height), controlPoint2: CGPointMake(page1.minX + 9.95, page1.minY + 0.35072 * page1.height))
        shapeCopy2Path.addCurveToPoint(CGPointMake(page1.minX + 13.49, page1.minY + 0.51220 * page1.height), controlPoint1: CGPointMake(page1.minX + 14.13, page1.minY + 0.35072 * page1.height), controlPoint2: CGPointMake(page1.minX + 14.44, page1.minY + 0.41433 * page1.height))
        shapeCopy2Path.addLineToPoint(CGPointMake(page1.minX + 10.99, page1.minY + 0.77980 * page1.height))
        shapeCopy2Path.addCurveToPoint(CGPointMake(page1.minX + 11.18, page1.minY + 0.84339 * page1.height), controlPoint1: CGPointMake(page1.minX + 10.55, page1.minY + 0.82709 * page1.height), controlPoint2: CGPointMake(page1.minX + 10.74, page1.minY + 0.84339 * page1.height))
        shapeCopy2Path.addCurveToPoint(CGPointMake(page1.minX + 15.46, page1.minY + 0.78298 * page1.height), controlPoint1: CGPointMake(page1.minX + 11.75, page1.minY + 0.84339 * page1.height), controlPoint2: CGPointMake(page1.minX + 13.62, page1.minY + 0.82376 * page1.height))
        shapeCopy2Path.addLineToPoint(CGPointMake(page1.minX + 16.54, page1.minY + 0.82377 * page1.height))
        shapeCopy2Path.addCurveToPoint(CGPointMake(page1.minX + 5.23, page1.minY + 1.00000 * page1.height), controlPoint1: CGPointMake(page1.minX + 12.04, page1.minY + 0.95100 * page1.height), controlPoint2: CGPointMake(page1.minX + 7.13, page1.minY + 1.00000 * page1.height))
        shapeCopy2Path.addLineToPoint(CGPointMake(page1.minX + 5.23, page1.minY + 1.00000 * page1.height))
        shapeCopy2Path.closePath()
        shapeCopy2Path.miterLimit = 4;

        shapeCopy2Path.usesEvenOddFillRule = true;

        buttonColor.setFill()
        shapeCopy2Path.fill()
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
