# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Palm Oil' do
    use_frameworks!
    # fabric - Crashlytics depends on it
    pod 'Fabric'
    # report bugs
    pod 'Crashlytics'
    # product layer SDK - API connector
    pod 'ProductLayerSDK', :git => 'https://github.com/Lweek/ProductLayer-SDK-for-iOS.git', :branch => 'swift3'
end

#target 'Palm OilTests' do
#end

