# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Palm Oil' do
    use_frameworks!
    # fabric - Crashlytics depends on it
    pod 'Fabric'
    # report bugs
    pod 'Crashlytics'
end

target 'Palm OilTests' do

end

